language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t abelyaev/docker-react -f Dockerfile.dev .  

script: 
  - docker run -e CI=true abelyaev/docker-react npm run test  